### PR TITLE
Added external input feature for debouncing non-pin signals

### PR DESCRIPTION
**Pull request by fkuersch**
It is now possible to use the debounce feature without
attaching a pin. You can provide your input state
via the update() method so you are able to debounce
any signal that comes into your mind.

### CODE REVIEW

**Comment by thomasfredericks** [comment]
What do you use this feature for?

**Comment by florian-kuersch** [comment]
Have a look at the Wiki: https://github.com/florian-kuersch/Bounce2/wiki
I updated that as well. There is an "External Input" example with a description why I implemented that.

**Comment by thomasfredericks** [comment]
That is some advanced use that requires specific external code. I try to keep my libraries very simple because I use them for teaching.

**Comment by fusionstream** [comment]
You can use this to read pins from expanders like the MCP23017 without having to use a library specific to that chip (like how I am currently using extended version of this library that is specific to the MCP23017).

**Comment by sdamaggio** [comment]
another use case where this could be useful is debouncing an analog sensor.
Once you compare the analog read to a trigger level it becomes digital and could be debounced using the library. But I understand the keep-it-simple approach.

**Comment by pictographer** [comment]
Capacitive touch sensing is another reason to use this proposed feature. The hardware for touch sensing is built into the Kinetis chips used by PJRC for the Teensy Arduino-compatible boards.

**Comment by thomasfredericks** [comment]
The current version of Bounce has the following methods that can be extended by a custom class for custom needs. If you do create a custom class, please share it.

```
virtual bool readCurrentState()
virtual void setPinMode(int pin, int mode) 
```

**Pull request closed without merging**
