### PR TITLE
Add component.mk and allow disabling Button class via Kconfig.

### PR DESCRIPTION
**Pull request by mkfrey**
The first commit of this pull request adds a component.mk file to allow using this project as a component of esp-idf (< 4.0).

The second commit adds a Kconfig file to allow disabling the Button class using the `make menuconfig` tool of the esp-idf. This is useful to avoid conflicts with other libraries implementing a class with the same name, e.g. the M5Stack library.

### CODE REVIEW

**Comment by thomasfredericks** [comment]
Hum, would it be simpler if the three classes were in separate files?

**Comment by mkfrey** [comment]
I don't know if this would change much. I think it would be better to put classes with such generic names into a namespace.

**Comment by thomasfredericks** [comment]
Since I just released Button, I will convert it to use namespaces even though it is not the «Arduino norm». It should not break user code that much... *gulp*

**Comment by thomasfredericks** [comment]
Ok, can you check out the new commit? I moved Button to Bounce2 namespace (Button2::Button).

**Comment by mkfrey** [comment]
Looks good from a first glance, I will test it at the start of next week.

**Comment by mkfrey** [comment]
Excuse my late response. The library now works fine from my perspective. I will change this merge request to only contain the component.mk file.

What I noticed when reviewing your commit is that Doxygen outputs are part of this repository and the commits. If this is what you want, I don't want to get in your way of making things. But in my opinion this causes a lot of clutter in the repository and commit history and therefore the Doxygen generated docs should not be part of the repository.

**Comment by thomasfredericks** [comment]
Yes. I understand about the docs. But I like that everything is bundled together. Thank you for your contribution!

**Comment by thomasfredericks** [comment]
@mkfrey What would you suggest for the docs?

**Comment by mkfrey** [comment]
The standard way seems to be to use Travis CI to automatically generate and commit documentation into a separate, orphaned branch "gh-pages".

**Pull request merged**
