### PR TITLE
Analog pins and modern C++

### PR DESCRIPTION
**Pull request by NelsonVides**
Implemented the possibility of an analog pin receiving different input values, like for example in this case:
https://drive.google.com/drive/folders/0B4EiesZHcweBQVY2NkdmRFhBNHc, where we can connect four buttons to just one pin, but each one through a step further down the line of resistors, will send a different voltage value. This way, the bouncer can clear all four buttons and tell to the Arduino which one was pressed.

Also changed the style for a more modern C++ code, like less macros and more constexpr, and more const-correctness.

### CODE REVIEW

**Comment by jokrug** [comment]
Good pull request. 
I just don't like the name SetBouncerFlag() because it does not describe, what the function does. 
Something like GetFlagBit() would describe it better.

**Comment by NelsonVides** [comment]
I'm also not sure about this name, but not sure about GetFlagBit() either. Sometimes we're using this function to get the flag (in read(), rose(), fell()), sometimes we're using it to set it (in update()). What this function is actually doing is returning a byte of zeroes and only one '1' on the n+1 place, which will then be operated with this->state.
Actually, what do you think of simply removing this function altogether and implementing instead something like
    constexpr uint8_t DEBOUNCED_STATE = 0b00000001;
    constexpr uint8_t UNSTABLE_STATE  = 0b00000010;
    constexpr uint8_t STATE_CHANGED   = 0b00001000;
and operate these values directly?

**Comment by NelsonVides** [comment]
Have a look at my "Bouncer3" version: https://github.com/NelsonVides/Bounce2/blob/Bouncer3/Bounce3.cpp. It breaks old code because now the bouncer is taking a pin from construction (I don't want to have a useless object in memory, I prefer to construct the object with all the information it needs from the very beginning. This will also be more efficient. In any case, what we can extract from there is how I handle the bit flags. As I mentioned in the previous comment, no strange function this time.
If you like that idea I can quickly implement it on Bounce2 and update the pull request. I think it's the best chance.

**Comment by PaulStoffregen** [comment]
I believe some Arduino boards are not able to use functions like pinMode in constructors.

A much better approach would be a constexpr constructor.  This does place severe limits on what you can do within the constructor.  But it solves the static initialization order issues that come up when other objects try to use your from their constructors.  Modern versions of gcc also are able to do much more optimization with classes that use constexpr constructors.

**Comment by NelsonVides** [comment]
Constexpr constructors got a lot more relaxed on C++17 but I think avr-gcc hasn't comply yet to 17's standards anayway (?).
I don't know about not being able to use pinMode in constructors, at least my Uno can. It's interesting to think about it, as pinMode is just another function to set registers DRC and PORT into the ATmega processor. Will do some research on this!
In any case, what I want to take from here for Bounce2 is how I handle that weird _BV macro. We need it only to return a byte of zeroes and a one on the specific place. So we can just get rid of this macro, or a constexpr function as well, by just using constexpr constants valued zeroes and a one on the desired place. Simplifies compilation, binary, and maintaining the code, as it looks more obvious what was the goal of the procedures: bitwise operation with the constants given on code. Have a look at my commit, I initially changed the macro to a constexpr function, but later I though we could get rid of the function altogether by using just well stated constants.

**Comment by thomasfredericks** [comment]
I like the replacement of the _BV macro.
The pin argument was purposely removed from the constructor (one of the main differences between Bounce1 and Bounce2) because it did not follow the Arduino standard where pins are never modified before setup().

**Comment by NelsonVides** [comment]
Aha, I had no idea of this Arduino standard. Can you let me know where can I find such documentation?
In any case, my Bouncer3 can stay on my experimental branches. Here I'm only submitting some clean-up on Bounce2.
Just cleaned the macro altogether, looks very neat now.

**Comment by thomasfredericks** [comment]
@NelsonVides It is not official. Wiring (aka Arduino) was built by a designer and not an engineer. Also, as it is based on Processing, its design attempts to avoid object oriented programming as much as possible :( . Also, everything is inconsistent. For example, in the Servo library, a pin is only attached in setup(). But in the Stepper library, pins must be defined in the constructor. 

As a general rule, to keep the library compatible with the target audience, I prefer not to constructor arguments, but methods for each individual setting. Constructor arguments can be confusing as to what they do.

**Comment by NelsonVides** [comment]
@thomasfredericks right, I understand. To be honest, I just started my first Arduino project a couple of weeks ago, I'm fond of C++ but don't know the familiarities of the Arduino libraries.
Anyway in this PR I'm not touching the constructor. That's on another experimental branch of mine. What do you think of this PR?

**Comment by thomasfredericks** [comment]
I will try it out next week.

**Comment by jokrug** [comment]
@NelsonVides 
I refactored the Bounce-class and also added the use of analog ports. 
Please have a look at [https://github.com/jokrug/Bounce2](https://github.com/jokrug/Bounce2)
- I missed the variable switch level in your pull request.
- The selection of analog mode with a define would mean that you can use the Bounce - class only for digital or analog pins in one project. I added a function attachAnalog() and use a memberfunction pointer to dynamically select the read function. 
- I replaced the macro and the "boolean magic" by inline functions with meaningful names. That makes it easier to understand the class.

The size of the lib increase only slightly. I compiled my test with the Arduino - IDE:
Original lib from Thomas:
Der Sketch verwendet 3.074 Bytes (10%) des Programmspeicherplatzes. 
Globale Variablen verwenden 250 Bytes (12%) des dynamischen Speichers,

Refactored lib:
Der Sketch verwendet 3.168 Bytes (10%) des Programmspeicherplatzes. 
Globale Variablen verwenden 258 Bytes (12%) des dynamischen Speichers,

I think, this overhead is acceptable, even if only very few people will use the analog option.

I would suggest to merge our code to a new pull request and close this one.

**Comment by NelsonVides** [comment]
@jokrug, good style this one :)

By pieces:
- The boolean magic. That was the worst part, it took me a while to realised we where setting bitwise flags here, and I also really don't like macros. Your option is very nice, just a bunch of obvious functions. They are not really inlined though. At least a good compiler optimisation flag should do it, but you're not assured they will. Mark them inline better. We also don't want the arduino to jump around with functions calls, just in case. On the other hand I'm not so fan of putting them as private functions of the class. It's pretty OOP, but this makes using your class less comprehensible (http://www.drdobbs.com/cpp/how-non-member-functions-improve-encapsu/184401197), and also this theoretically makes the vtable for the class a couple of bytes longer, which is probably the reason your code got bigger (also, your example cannot compile Thomas' code because you're using functions he didn't declare, but I guess you mean a code that simply declares a Bouncer object), and with only 2kb of memory I'm a bit hysteric on saving bytes on the Arduino. As they don't need access to any private data of the object, I'd rather leave them on an anonymous namespace on the .cpp translation unit. This way they're anonymous to the outside world and you'll get linker errors if you try to call them externally (a common way to 'privatise' stuff on a functional approach).
Also, I'm a total fan of constexpr: in this case it'll do the same than `static const`, but in other context it doesn't have to. Anyway in this case it's pretty much just taste.
- The selection of analog mode, that's totally true, that means we can only use one of them, and this is a very interesting problem to solve... Solutions to use both would be to have a children class implementing the analog functionality, or, as you do, making a function pointer to the function we want to use to read: that's a genius approach.
The only problem I see with this (apart from the fact that we might not be sure if the compiler is inlining them or calling them at runtime), is that I want my Bouncer to tell me what value was read exactly. I think my Bouncer should just cure the mechanical noise, which is what "debouncing" means, and then the responsibility to interpret this value should be elsewhere. The 'S' in the SOLID principles.
This opens to me an interesting approach. I think your code won't be able to distinguish two buttons being pressed at the same time, but you just give me an idea how to solve this problem... gotta experiment for another Pull Request :D

What @thomasfredericks thinks of this?

**Comment by jokrug** [comment]
@NelsonVides: nice and interesting discussion here. I like that.
- inline: It cannot harm to put an inline in front of the functions. At least in the Arduino-IDE it doesn't seem to make a difference. I compiled the same ino with and without the inline keyword to exactly the same binary size.
- Make the functions non-member: I read the article and found it interesting. Nevertheless I cannot see how the class would look better, if we move the functions out of the class. They use the member variable state and they are private functions that only should be used inside the class. 
- constexpr: What is the advantage over static const? From time to time I use an old 8051 compiler for an existing project. With a few stubs for the Arduino functions I could easily use the Bouncer in that project, but I don't think, the compiler would know constexpr. In the world of microcontrollers you often have to deal with old compilers.
- The increase of binary size mentioned in my previous post is mainly a result of the additional features I added to the class. I compared the original class from Thomas with my class, that additionally includes the analog functions. Only a few people will use the feature, so the increase should be neglectable. I thought, about 100 bytes would be ok.
- After your explanation I'm not sure, how your implementation of analog buttons should be used. Could you add an example.ino? My interpretation was strait forward: consider the button as pressed, when the reading of the analog input is inside a given range for a certain time. I put the schema drawn in ASCII-art in /examples/bounce_analog.ino on a bread board and it worked perfect. If the voltage ranges overlap, it would be possible to detect two successive pressed buttons, but never say button 1 and button 4. But I cannot see, how this could be done at all.
- The function pointer is more c-style. The syntax is difficult and you have to use it with great care. I therefore made another test and split the Bounce class into three classes: BouceBase, Bouce and BounceAnalg. The bounceRead() function is now virtual and can be overwritten in the derived classes. That way I let C++ deal with the function pointer. Looks nice, works as before, but comes to the price of another 200 bytes +. I will upload this version to github the next days so that you can have a look at it.

**Comment by NelsonVides** [comment]
Love the topic @jokrug :)

First mention that I'm not using the Arduino IDE nor .ino files, I'm developing on Eclipse using the CDT standard extension, with compiler avr-gcc 4.9.2. Hence, all my files are .cpp and I can freely send flags to the compiler: I have -stl=C++14 activated (sadly avc-gcc doesn't comply to C++17 yet). So yeah, constexpr came into play after ++11, older compilers would have a problem. But I believe Arduino IDE already comes with avr-gcc and C++11 by default... This might be just up to testing.

- For examples of my usage, have a loop at my Arduino Controller project: https://github.com/NelsonVides/ArduinoController.

- inline: as little as they're used, the compiler might just optimise them inlining, but you can't be promised such. That's where constexpr is even a stronger promise than inlines or optimisations. In any case, it doens't hurt to keyword inline them, in case a compiler doesn't optimise already.

- constexpr: a static const doesn't necessarily have to be calculated at compile time, and it might also live on its own memory space. A constexpr, if the compiler cannot calculate it, will throw an error (I'm simplifying here though). In any case, for just an int, there is no difference, it's just my constexpr-habit. I can easily revert that on the PR in case of older compilers.

- Non-member functions: the thing is that they're not really using private data: they just need a byte as input, and give back a new byte as output. Just look here: https://github.com/NelsonVides/Bounce2/blob/f26ad19ae3137c5941766f171e5dfcc9802dbe69/Bounce2.cpp#L12 They could be reusable for something else, or they could be just inlined, if necessary then hidden, and minimizing the vtable in case a compiler optimisation doesn't.

- My implementation of the analogs will just give back the value that has been read, and someone else will interpret it. This way, I only need 1 bouncer per pin, and also, the bouncer is not doing too much, which is later better to maintain. Have a look at my project I mentioned above. About how to recognise two buttons... Well, the voltages add up, and the _interpreter_ could just read the exact value and know which values would mean which buttons adding up. The only problem is if a button is already throwing 1023 (that is, the full 5V), in such case this button would shut up all the others on his line. I need to find a way, electrically speaking, to make all buttons throw below 1023 so I can distinguish them.

- On a Uno, with only 2000bytes of memory, when I'm implementing radio receivers, events, 16 buttons, weather measures... 100bytes is definitely too much :(

**Comment by thomasfredericks** [comment]
Here is my test code:
```
// Detect the falling edge of multiple buttons.
// Eight buttons with internal pullups.
// Toggles a LED when any button is pressed.
// Buttons on pins 2,3,4,5,6,7,8,9

// Include the Bounce2 library found here :
// https://github.com/thomasfredericks/Bounce2
#include <Bounce2.h>

#define LED_PIN 13

#define NUM_BUTTONS 8
const uint8_t BUTTON_PINS[NUM_BUTTONS] = {2, 3, 4, 5, 6, 7, 8, 9};

int ledState = LOW;

Bounce * buttons = new Bounce[NUM_BUTTONS];

void setup() {

  for (int i = 0; i < NUM_BUTTONS; i++) {
    buttons[i].attach( BUTTON_PINS[i] , INPUT_PULLUP  );       //setup the bounce instance for the current button
    buttons[i].interval(50);              // interval in ms
  }

  // Setup the LED :
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, ledState);


}

void loop() {

  bool needToToggleLed = false;


  for (int i = 0; i < NUM_BUTTONS; i++)  {
    // Update the Bounce instance :
    buttons[i].update();
    // If it fell, flag the need to toggle the LED
    if ( buttons[i].fell() ) {
      needToToggleLed = true;
    }
  }

  // if a LED toggle has been flagged :
  if ( needToToggleLed ) {
    // Toggle LED state :
    ledState = !ledState;
    digitalWrite(LED_PIN, ledState);
  }
}
```

With my original library, and an Arduino Uno, it compiles at 2000 bytes. 

@jokrug your code did not initially compile. It has {  } at line 62 of Bounce2.h that the Arduino IDE does not like. But even when corrected, **your code does not work**. It compiles but does not light up the LED. When compiled, the total size was 2026 bytes.

Basically I do not want to change anything in the library that is not broken. The only change I would be willing to make is to make "inline virtual int bounceRead() {digitalRead(mPin);} so that the class can be extended by third party libraries.

**Comment by thomasfredericks** [comment]
@jokrug I think you are missing a return in bounceRead().

**Comment by thomasfredericks** [comment]
The code has been updated.

**Pull request closed without merging**
