### PR TITLE
BounceButton - a class for buttons

### PR DESCRIPTION
**Pull request by NoobTracker**
The BounceButton class adds the setInvert() function to the Bounce class, which can be used to invert the new pressed() and released() functions. read() is also adjusted so that you can use setInvert() with it. This class is intended for inverting a button when using INPUT_PULLUP.

### CODE REVIEW

**Comment by thomasfredericks** [comment]
Hi @NoobTracker,

I made a branch ( https://github.com/thomasfredericks/Bounce2/tree/Button ) with the basic idea behind your merge request. Please check the buttonClass example. I did not test it yet. I included the class directly into Bounce2.h

**Comment by NoobTracker** [comment]
Hi,
the idea with setPressedState () is really good, it is more understandable than setInvert (). The program should work. With stateForPressed, however, the default value is 0, which immediately activates the inversion. That should be changed. I would also `return !(getStateFlag(DEBOUNCED_STATE) ^ stateForPressed) && getStateFlag(CHANGED_STATE);` use for pressed rather than the current program and maybe outsource the functions to the .cpp file. But that's your decision. In any case, thank you for taking care of the program.

**Comment by NoobTracker** [comment]
Oh, and the example doesn't work because you only switch on the LED if the button was pressed exactly during the last update. Then she goes out again. You would have to make ```
if ( buttonA.pressed()  || buttonB.pressed()  ) {
    digitalWrite(LED_PIN, HIGH );
  } 
  else {
    digitalWrite(LED_PIN, LOW );
  }
``` 

  ```
if ( buttonA.pressed()  || buttonB.pressed()  ) {
    digitalWrite(LED_PIN, HIGH );
  } 
  if ( buttonA.released()  || buttonB.released()  ) { {
    digitalWrite(LED_PIN, LOW );
  }
```
You could also make `#define LED_PIN 13` `#define LED_PIN LED_BUILTIN`.

**Comment by thomasfredericks** [comment]
Wow, thanks for the error checking. I really messed up ;) I will correct it.
I prefer not to create additional header files to reduce potential conflicts with other libraries. Although they could be hidden in a subfolder inside «src».

**Comment by thomasfredericks** [comment]
Corrections were uploaded

**Comment by jamesmyatt** [comment]
"setPressedState" is much better. I have a class in my current project that's very similar. I think you can re-use the state attribute to avoid increasing memory usage.

**Comment by thomasfredericks** [comment]
> Would it be possible to close this PR and open a new one for your "Button" branch?

Yes @jamesmyatt

**Pull request closed without merging**
